# Generated by Django 2.2 on 2019-05-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loggerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggerBuffer', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='IP',
        ),
    ]
